// server/src/utils/emailTemplates.js
const CLIENT_URL = process.env.CLIENT_URL || 'http://localhost:5173';
const YEAR = new Date().getFullYear();

const header = (title, sub = '') => `<div style="background:linear-gradient(135deg,#1e3a8a,#3b82f6);color:#fff;padding:40px 30px;text-align:center"><h1 style="margin:0;font-size:32px">${title}</h1>${sub ? `<p style="margin:10px 0 0;font-size:14px;opacity:.9">${sub}</p>` : ''}</div>`;
const footer = () => `<div style="background:#f9fafb;padding:25px;text-align:center;border-top:1px solid #e5e7eb"><p style="font-size:13px;color:#9ca3af;margin:5px 0">© ${YEAR} ConServe - NEUST</p></div>`;
const button = (url, text) => `<div style="text-align:center;margin:30px 0"><a href="${url}" style="display:inline-block;padding:16px 48px;background:#1e3a8a;color:#fff;text-decoration:none;border-radius:10px;font-weight:bold">${text}</a></div>`;
const box = (content, color = '#3b82f6') => `<div style="background:${color}15;padding:20px;border-left:4px solid ${color};margin:20px 0;border-radius:8px">${content}</div>`;

export const welcomeEmailTemplate = (user) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Welcome to ConServe', 'Research Repository')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${user.firstName} ${user.lastName}</strong>,</p><p style="color:#374151">Thank you for registering with ConServe!</p>${box(`<p style="margin:0;color:#92400e;font-weight:bold">⏰ Pending Approval</p><p style="margin:10px 0 0;color:#92400e">You'll receive another email once approved (24-48 hours).</p>`, '#f59e0b')}<div style="background:#f9fafb;padding:20px;margin:20px 0;border-radius:8px"><p style="margin:0 0 10px;font-weight:bold">📋 Details:</p><p style="margin:5px 0"><strong>Email:</strong> ${user.email}</p><p style="margin:5px 0"><strong>ID:</strong> ${user.studentId}</p><p style="margin:5px 0"><strong>Role:</strong> ${user.role}</p></div></div>${footer()}</div></body></html>`;

export const approvalEmailTemplate = (user) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Account Approved', 'Access Granted')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${user.firstName} ${user.lastName}</strong>,</p><p style="color:#374151">Your account has been <strong>approved</strong>!</p>${box(`<p style="margin:0;color:#166534;font-weight:bold">✓ You can now:</p><ul style="color:#166534;margin:10px 0;padding-left:20px"><li>Browse papers</li><li>Submit research</li><li>Bookmark papers</li></ul>`, '#10b981')}${button(CLIENT_URL + '/login', 'Login Now')}</div>${footer()}</div></body></html>`;

export const passwordResetEmailTemplate = (user, token) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Password Reset', 'Security Alert')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${user.firstName}</strong>,</p><p style="color:#374151">Reset your password using the button below.</p>${box(`<p style="margin:0;color:#92400e;font-weight:bold">⏰ Expires in 1 hour</p>`, '#f59e0b')}${button(CLIENT_URL + '/reset-password?token=' + token, 'Reset Password')}</div>${footer()}</div></body></html>`;

export const passwordResetConfirmationTemplate = (user) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Password Reset Complete', 'Secure')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${user.firstName}</strong>,</p><p style="color:#374151">Your password has been successfully reset.</p>${button(CLIENT_URL + '/login', 'Login Now')}</div>${footer()}</div></body></html>`;

export const adminNewUserNotificationTemplate = (user) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('New User', 'Action Required')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">New registration:</p><div style="background:#eff6ff;padding:20px;margin:20px 0;border-radius:8px"><p style="margin:5px 0"><strong>Name:</strong> ${user.firstName} ${user.lastName}</p><p style="margin:5px 0"><strong>Email:</strong> ${user.email}</p><p style="margin:5px 0"><strong>ID:</strong> ${user.studentId}</p><p style="margin:5px 0"><strong>Role:</strong> ${user.role}</p></div>${button(CLIENT_URL + '/dashboard', 'Review User')}</div>${footer()}</div></body></html>`;

export const researchSubmissionNotificationTemplate = (research, author) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('New Research', 'Review Required')}<div style="padding:40px 30px"><p style="color:#374151">New paper submitted:</p><div style="background:#eff6ff;padding:20px;margin:20px 0;border-radius:8px"><p style="margin:5px 0"><strong>📄 Title:</strong> ${research.title}</p><p style="margin:5px 0"><strong>👤 Author:</strong> ${author.firstName} ${author.lastName}</p><p style="margin:5px 0"><strong>📧 Email:</strong> ${author.email}</p><p style="margin:5px 0"><strong>📅 Date:</strong> ${new Date(research.createdAt).toLocaleDateString()}</p></div>${button(CLIENT_URL + '/dashboard?adminReview=' + research._id, 'Review Paper')}</div>${footer()}</div></body></html>`;

export const researchApprovedTemplate = (research, author) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Paper Approved', 'Published')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${author.firstName}</strong>,</p><p style="color:#374151">Congratulations! Your paper has been <strong>approved</strong>!</p>${box(`<p style="margin:0;color:#166534;font-weight:bold">✓ ${research.title}</p><p style="margin:10px 0 0;color:#166534">Now accessible to all users.</p>`, '#10b981')}${button(CLIENT_URL + '/research/' + research._id, 'View Paper')}</div>${footer()}</div></body></html>`;

export const researchRevisionRequestedTemplate = (research, author, notes) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Revision Requested', 'Action Required')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${author.firstName}</strong>,</p><p style="color:#374151">Your paper requires revisions.</p>${box(`<p style="margin:0;color:#92400e;font-weight:bold">📋 ${research.title}</p><p style="margin:10px 0 0;color:#92400e">${notes || 'Please review feedback.'}</p>`, '#f59e0b')}${button(CLIENT_URL + '/dashboard', 'View Details')}</div>${footer()}</div></body></html>`;

export const researchRejectedTemplate = (research, author, notes) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Review Update', 'Further Work Needed')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${author.firstName}</strong>,</p><p style="color:#374151">Your paper requires additional work.</p>${box(`<p style="margin:0;color:#92400e;font-weight:bold">📋 ${research.title}</p><p style="margin:10px 0 0;color:#92400e">${notes || 'Please review guidelines.'}</p>`, '#f59e0b')}${button(CLIENT_URL + '/dashboard', 'Go to Dashboard')}</div>${footer()}</div></body></html>`;

export const facultyReviewNotificationTemplate = (research, reviewer, comments) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('Faculty Review', 'Feedback Available')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello <strong>${research.submittedBy.firstName}</strong>,</p><p style="color:#374151">Your paper received faculty feedback.</p><div style="background:#eff6ff;padding:20px;margin:20px 0;border-radius:8px"><p style="margin:5px 0"><strong>📄 Paper:</strong> ${research.title}</p><p style="margin:5px 0"><strong>👤 Reviewer:</strong> ${reviewer.firstName} ${reviewer.lastName}</p><p style="margin:15px 0 5px;font-weight:bold">💬 Comments:</p><p style="margin:0">${comments}</p></div>${button(CLIENT_URL + '/research/' + research._id, 'View Review')}</div>${footer()}</div></body></html>`;

export const facultyApprovedPaperNotificationTemplate = (research) => `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:20px;background:#f3f4f6"><div style="font-family:Arial;max-width:600px;margin:0 auto;background:#fff">${header('New Approved Paper', 'Ready for Faculty Review')}<div style="padding:40px 30px"><p style="font-size:18px;color:#111827">Hello Faculty,</p><p style="color:#374151">A new research paper has been <strong>approved by admin</strong> and is now ready for your optional review.</p>${box(`<p style="margin:0;color:#166534;font-weight:bold">📄 ${research.title}</p><p style="margin:10px 0 0;color:#166534">You can now provide faculty feedback on this paper.</p>`, '#10b981')}${button(CLIENT_URL + '/research/' + research._id, 'Review Paper')}<p style="color:#6b7280;font-size:14px;margin-top:20px">Note: Your review is advisory and helps ensure quality standards.</p></div>${footer()}</div></body></html>`;